name: Build and run tests
on:
  pull_request:
    paths:
      - '**.cs'
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6
    - name: Install dependencies
      run: dotnet restore --no-cache
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
